---
workspaces:
  - angular
  - bzlmod
  - nestjs
  - protobufjs
  - ts_project_transpiler
  - write_source_files

tasks:
  test:
    flags:
      # Don't try and auto detect the cc toolchain, as we use our own gcc toolchains
      - --action_env=BAZEL_DO_NOT_DETECT_CPP_TOOLCHAIN=1
